version: "3"

services:
  db:
    image: mysql:latest
    container_name: rails6_mysqldb
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    container_name: rails6_redis
    ports:
      - 63790:6379
  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: rails6_backend
    container_name: rails6_backend
    tty: true
    stdin_open: true
    command: bash -c 'rm -f tmp/pids/server.pid && bundle install && rails s -p 3000 -b 0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      EDITOR: nano
    volumes:
      - ./:/rails6
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rails6_phpmyadmin
    links:
      - db:mysql
    ports:
      - 8888:80
